Bugfix #177533187 – Log an error if a metadata value is missing
ebi-gene-expression-group/atlas-web-single-cell pull request #185
Opened 2021-07-26 20:28 UTC by alfonsomunozpomer

Rather than showing a cryptic 400 error we use the placeholder “Not available” for missing metadata values. I haven’t included a test because:
- We need to use an incorrect condensed SDRF file
- Verifying that the logger adds an error message would mean a mocked logger, a spy, or a somewhat convoluted constructor just for the sake of testing

In summary: testing a side effect as a consequence of an edge case doesn’t seem like the most solid business logic and should happen rarely.

2021-07-27 11:03 UTC, alfonsomunozpomer commented
Fixes https://github.com/ebi-gene-expression-group/atlas-web-single-cell/issues/162.

2021-08-02 15:51 UTC, haideriqbal requested changes
Not much, just one comment! Otherwise LGTM!

2021-08-02 15:51 UTC, haideriqbal commented on app/src/main/java/uk/ac/ebi/atlas/experimentpage/metadata/CellMetadataDao.java
> +                                    !tuple.getStrings(METADATA_VALUE_TARGET_FIELD_NAME).isEmpty()) {
Wouldn't this condition result in the correct Cell Ids being logged as errors? Say for example, `cell_id` is `not null` and its name is `xyz` then this `if` condition would evaluate to true. As it has a `!` before `isEmpty()`.

Or am I missing something here?

2021-08-03 13:38 UTC, haideriqbal approved these changes
All Good!

2021-08-03 13:46 UTC, merged