Feature/176092178 add hdf5 project file to download
ebi-gene-expression-group/atlas-web-single-cell pull request #235
Opened 2022-03-30 09:35 UTC by lingyun1010

This PR comes with https://github.com/ebi-gene-expression-group/atlas-web-core/pull/105

2022-04-08 09:36 UTC, upendrakumbham commented on app/src/main/java/uk/ac/ebi/atlas/download/ExperimentFileLocationService.java
> +                return dataFileHub.getSingleCellExperimentFiles(experimentAccession).projectHdf5.getPath();
Can you think of any test case to test this new file type?

2022-04-08 09:37 UTC, upendrakumbham requested changes
The code looks fine, please cover tests for this new feature.

2022-04-13 09:56 UTC, lingyun1010 commented on app/src/main/java/uk/ac/ebi/atlas/download/ExperimentFileLocationService.java
> +                return dataFileHub.getSingleCellExperimentFiles(experimentAccession).projectHdf5.getPath();
We don't really have HDF5 file in the existing test experiments.

2022-04-13 19:52 UTC, upendrakumbham approved these changes
LGTM!

2022-04-14 08:11 UTC, merged