Clear endpoints for cell type marker gene heatmap
ebi-gene-expression-group/atlas-web-single-cell pull request #257
Opened 2022-06-16 10:32 UTC by lingyun1010

Remove the getting cell types endpoint and refactor cell type marker gene heatmap data endpoint by removing cell type variables.

2022-08-18 07:02 UTC, upendrakumbham commented on app/src/main/java/uk/ac/ebi/atlas/experimentpage/markergenes/MarkerGeneService.java
> +                        .getCellTypeMarkerGenes(
can you refactor tests as well?

2022-12-14 19:55 UTC, alfonsomunozpomer requested changes
Please rebase on top of `develop` and get this branch tested.

2023-03-20 15:08 UTC, alfonsomunozpomer approved these changes
All good. You’ll need to merge again `develop`. Sorry about that! It shouldn’t be much of a problem, though.

2023-03-31 09:21 UTC, upendrakumbham approved these changes
ALGTM!

2023-06-14 14:10 UTC, merged