Add species filter to cell type wheel
ebi-gene-expression-group/atlas-web-single-cell pull request #310
Opened 2022-12-15 19:01 UTC by alfonsomunozpomer

2022-12-19 10:54 UTC, ke4 requested changes
I added some really tiny comments. Could you review it, please?
Otherwise it looks fine for me 👍

2022-12-19 10:54 UTC, ke4 commented on app/src/main/java/uk/ac/ebi/atlas/search/metadata/CellTypeWheelDao.java
> +// '
If we need this comment here, maybe a short 1 sentence summary would be good at the top of these lines.

2022-12-19 10:54 UTC, ke4 commented on app/src/main/java/uk/ac/ebi/atlas/search/metadata/CellTypeWheelDao.java
> +    public ImmutableList<ImmutableList<String>> facetSearchCtwFields(String searchTerm, String species) {
Could we add `.addFilterFieldByTerm(CTW_ORGANISM, species)` conditionally if the `species` parameter is not `null`? If that works, then we could remove the other `facetSearchCtwFields` method.

2022-12-19 10:54 UTC, ke4 commented on app/src/main/java/uk/ac/ebi/atlas/search/metadata/CellTypeWheelService.java
> +        return explodeTuples(cellTypeWheelDao.facetSearchCtwFields(searchTerm));
If you could refactor the `facetSearchCtwFields`, then please also change this line of code. Thanks

2022-12-22 13:53 UTC, alfonsomunozpomer commented
@ke4 Please have another look. I reworked the controller/service/DAO classes to delay the optional behaviour all the way to the DAO class, so we don’t have overloaded methods. Initially I thought this was clearer in terms of intent, but maybe this is clearer and easier to read.

2022-12-22 17:03 UTC, ke4 approved these changes
@alfonsomunozpomer Thanks for the changes.
LGTM 👍

2022-12-22 17:23 UTC, merged