Chore – Remove experiment design
ebi-gene-expression-group/atlas-web-single-cell pull request #316
Opened 2023-02-03 16:22 UTC by alfonsomunozpomer

Accompanied by https://github.com/ebi-gene-expression-group/atlas-web-core/pull/121

2023-02-27 16:09 UTC, ke4 requested changes
I added some tiny comments. Could you review them please.
Thanks

2023-02-27 16:09 UTC, ke4 commented on app/src/main/java/uk/ac/ebi/atlas/experimentpage/tabs/ExperimentPageContentSerializer.java
> +//        var experimentDesignJson =
Could you remove these commented lines, please?

2023-02-27 16:09 UTC, ke4 commented on jenkins-k8s-pod.yaml
> -      #args: [ "-c", "kubectl scale --replicas=2 solrcloud scxa && sleep 2h" ]
This is already in your other [PR: Enable SolrCloud cluster scaler pod](https://github.com/ebi-gene-expression-group/atlas-web-single-cell/pull/323). I would remove this from this one.

2023-02-27 18:38 UTC, alfonsomunozpomer commented on jenkins-k8s-pod.yaml
> -      #args: [ "-c", "kubectl scale --replicas=2 solrcloud scxa && sleep 2h" ]
We need this to test in Jenkins. However, since I merged the SolrCloud scaler PR, it won’t be part of the diff of this branch when merging, right?

2023-02-28 09:19 UTC, ke4 commented on jenkins-k8s-pod.yaml
> -      #args: [ "-c", "kubectl scale --replicas=2 solrcloud scxa && sleep 2h" ]
I think, right now it is. Probably one of the source of your merge conflict. ;-)

2023-02-28 13:49 UTC, upendrakumbham reviewed
One quick question - why are we not deleting this code 

 ```
public JsonObject getExperimentDesign(String experimentAccession,
                                          JsonObject experimentDesignTableAsJson,
                                          String accessKey) {
        var result = new JsonObject();

        result.add("table", experimentDesignTableAsJson);
```
from the `ExperimentPageContentService` class. Any reason to keep it?

2023-02-28 14:23 UTC, alfonsomunozpomer commented
> One quick question - why are we not deleting this code
> 
> ```
> public JsonObject getExperimentDesign(String experimentAccession,
>                                          JsonObject experimentDesignTableAsJson,
>                                          String accessKey) {
>        var result = new JsonObject();
> 
>        result.add("table", experimentDesignTableAsJson);
> ```
> 
> from the `ExperimentPageContentService` class. Any reason to keep it?

Good catch. No, no reason at all. I’ve deleted it now.

2023-02-28 14:25 UTC, ke4 approved these changes
LGTM

2023-03-01 11:06 UTC, upendrakumbham approved these changes
All looks good to me!

2023-03-01 11:17 UTC, merged