Update tsne-plot package
ebi-gene-expression-group/atlas-web-single-cell pull request #364
Opened 2023-10-25 10:43 UTC by lingyun1010

The update in the tsne plot is here https://github.com/ebi-gene-expression-group/atlas-components/pull/144.

2023-10-31 10:40 UTC, ke4 requested changes
Just a tiny change request, other than that it is all fine. Thanks

2023-10-31 10:40 UTC, ke4 commented on app/src/main/javascript/bundles/experiment-page/src/TSnePlotViewRoute.js
> +      //selectedClusterByCategory: !isNaN(search.colourBy) ? `clusters` : `metadata`,
Could you please remove this line if we don't need it. Thanks

2023-10-31 15:16 UTC, upendrakumbham approved these changes, later dismissed
I tested this PR in my local after running front-end recompile and build and deploy scripts.
All looks great to me, actually Gray colour plot issue also fixed it seems. I didn't see it in the PR.

2023-11-01 11:35 UTC, ke4 approved these changes
LGTM

2023-11-01 12:03 UTC, merged